name: tehran_exchange
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  dots_indicator: ^2.1.0
  provider: ^6.0.3
  http: ^0.13.4
  dio: ^4.0.6
  # qr_code_scanner: ^0.7.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansWeb.ttf
        - asset: assets/fonts/BElham.ttf
          weight: 700
        - asset: assets/fonts/BKoodakBold.ttf
          weight: 300
    - family: Yekanbakh
      fonts:
        - asset: assets/font/Yekan Bakh EN 04 Regular.ttf
        - asset: assets/font/Yekan Bakh EN 07 Heavy.ttf
        - asset: assets/font/Yekan Bakh EN 08 Fat.ttf
          weight: 300

